name: Saludo usando variables
on:
  push
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: saludar
        run : echo "$SALUDO, $env.NOMBRE y $NOMBRE2. Hoy es $DIA_DE_SEMANA"
        env:
          NOMBRE2: Villanos
